# Generated by Django 5.0.7 on 2024-08-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_remove_driver_license_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="license_number",
            field=models.CharField(default="dv34565F_w", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
