# Generated by Django 5.0.7 on 2024-08-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver"},
        ),
    ]
